### ISSUE TITLE
Labels drop some diacritics

### ISSUE THREAD

**Issue by RicoElectrico** [lukasmartinelli/osm-liberty#1]
Have a look at: http://osm-liberty.lukasmartinelli.ch/#12.7/54.5408/18.5292
Obłuże is rendered as "Obue".

**Comment by iav** [comment]
Same for Latvian letters.
Russial letters (not ascii-based alphabet) missed completely.

**Comment by mkyral** [comment]
The same issue for Czech special characters like "ě", "š", "č", "ř", "ž"...

**Comment by Maturion** [comment]
Names written in the Cyrillic alphabet are not rendered at all. This doesn't seem to be caused by the data source as it doesn't make any difference when I use Mapbox as my source.

**Comment by orangemug** [comment]
I tried switching out 'Roboto' for 'Open Sans' and that seemed to fix the issue. I'm not sure why the 'Roboto' used here is missing those glyphs though

**Comment by orangemug** [comment]
I just tried re-generating the _Roboto_ and _Roboto Condensed_ glyphs and that seems to resolve the issue, I'll do some more testing later on, and all going well submit a PR

**Comment by orangemug** [comment]
@lukasmartinelli so it looks like something went wrong when you generated the font glyphs. I've regenerated them using this script https://github.com/orangemug/font-glyphs which output the glyphs as artifacts https://circleci.com/gh/orangemug/font-glyphs/7#artifacts/containers/0

Direct link for the glyphs here https://7-69746731-gh.circle-artifacts.com/0/tmp/circle-artifacts.EXfFT2E/Roboto.tar.gz

Before
<img width="552" alt="before" src="https://cloud.githubusercontent.com/assets/235915/19015503/a1fdb47a-87fd-11e6-9a16-4efd4c5d49e8.png">

After
<img width="553" alt="after" src="https://cloud.githubusercontent.com/assets/235915/19015504/ac9752b0-87fd-11e6-9b82-bcfb09213db1.png">

I was going to submit a PR however I don't think the binary font files should exist in the repo because it makes the clone painful (large file size). Maybe instead we should put the font files somewhere and download them with a init script.

What do you think?

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli so it looks like something went wrong when you generated the font glyphs. I've regenerated them using this script https://github.com/orangemug/font-glyphs which output the glyphs as artifacts https://circleci.com/gh/orangemug/font-glyphs/7#artifacts/containers/0

Easiest way to solve the font problem would be to point them to https://github.com/klokantech/klokantech-gl-fonts which contains patched Google Noto fonts with all Glyphs. I think they are available via GitHub pages as well.

**Comment by orangemug** [comment]
The idea of generating them via CI was that the script and version of font used was publicly accessible. Reasons being:
- It turns out Roboto gets quite a few fixes https://github.com/google/roboto/releases
- Easier to identify problems with font glyph generation because you know how it was generated 

But honestly either way is fine with me for now.

**Comment by lukasmartinelli** [comment]
> The idea of generating them via CI was that the script and version of font used was publicly accessible. Reasons being:
> 
> It turns out Roboto gets quite a few fixes https://github.com/google/roboto/releases
> Easier to identify problems with font glyph generation because you know how it was generated
> But honestly either way is fine with me for now.

If you provide a PR pointing to the patched Roboto font from the CI that's fine for me - will accept it.

**Comment by orangemug** [comment]
Thanks, I'll look into pushing to gh-pages from circle ci for that repo.

Note that'll probably be after the weekend now.
