### ISSUE TITLE
Style also POI subclass?

### ISSUE THREAD

**Issue by pathmapper** [lukasmartinelli/osm-liberty#113]
from https://github.com/maputnik/osm-liberty/pull/110#discussion_r1358866118

OSM Liberty style uses icons very basically: it's just "icon-image": "{class}_11".
In the future the subclass could be used, yes. But how?

specify an icon for each subclass (or maybe for each class-subclass pair)
=> are there some features with an empty subclass? if so, do we need a fallback?
=> will we accept to duplicate lots of icons? or can we create aliases in sprite.json?
for each subclass (or class-subclass pair), create rules in the style that select an icon

...what are your thoughts?

**Comment by pathmapper** [comment]
I would consider styling of `subclass` optional.

One approach would be to introduce new `poi_subclass` layers using the same approach as for `class` -> "`icon-image": "{subclass}_11"` in combination with filters to avoid styling the `class` and `subclass` of a POI (exclude it from `class` styling when using the `subclass` and include it for `subclass` styling)

> are there some features with an empty subclass? 

good question :wink: 

> if so, do we need a fallback?

no, because we would only style `subclass` intentional (if there is one) 

> will we accept to duplicate lots of icons?

no

> or can we create aliases in sprite.json?

aliases could work, never tried it. but I think there is no need, because we would only want to style a subclass if there is a dedicated icon for it available.

**Comment by pathmapper** [comment]
Giving this some more thoughts, I think we should keep the existing layers and use a match expression like the following to style subclass:

`"icon-image": ["match", ["get", "subclass"], ["florist", "furniture"], ["concat", ["get", "subclass"], "_11"], ["concat", ["get", "class"], "_11"]]`

After https://github.com/maputnik/osm-liberty/issues/115 the expression could be reduced to:

`"icon-image": ["match", ["get", "subclass"], ["florist", "furniture"], ["get", "subclass"], ["get", "class"]]`

**Comment by etiennejourdier** [comment]
Hello,

It seems to me that the expression `"icon-image": ["match", ["get", "subclass"], ["florist", "furniture"], ["get", "subclass"], ["get", "class"]]` is not working to show the sport icon (subclass) instead of the pitch icon (class)

(In the 2 examples below, I printed the subclass instead of the name in the text layout field.)

For example, I was expecting the match expression to give this result, with different icons for soccer and tennis pitches:
![image](https://github.com/user-attachments/assets/620d4d35-fc97-4385-ba1e-d92366fe7e01)
(To get this result I had to used `"icon-image": "{subclass}"` which is not satisfactory because it does not have the fallback) 

whereas the match expression gives this result, with always the pitch icon whatever the sport:
![image](https://github.com/user-attachments/assets/ab6dc69e-a9da-4315-a775-b971ba45333f)

I did not check if it is working for other subclass icons (when the class is not pitch).
