### ISSUE TITLE
Self hosted offline 

### ISSUE THREAD

**Issue by 386sx** [lukasmartinelli/osm-liberty#82]
I'm using an openmatiles.com self-hosted server with default styles and additionally osm-liberty.
All styles work fine when creating offlinepacks with react-native-mapbox-gl apart from osm-liberty.
Is there anything that I need to configure or consider when trying to use this style offline?
It's working perfectly fine when connected, but it won't cache the last seen map view or work when downloaded as a pack.

**Comment by pathmapper** [comment]
Hi @386sx,

for the OSM Liberty style you need:
- vector tiles (OpenMapTiles)
https://github.com/maputnik/osm-liberty/blob/eb04537a675f44e849796e9a83d52e10fd41d242/style.json#L11
- raster tiles
https://github.com/maputnik/osm-liberty/blob/eb04537a675f44e849796e9a83d52e10fd41d242/style.json#L17
- sprite
https://github.com/maputnik/osm-liberty/blob/eb04537a675f44e849796e9a83d52e10fd41d242/style.json#L22
- glyphs
https://github.com/maputnik/osm-liberty/blob/eb04537a675f44e849796e9a83d52e10fd41d242/style.json#L23

If the style isn't working, I suspect this is because you don't have to all these locally.

**Comment by 386sx** [comment]
Ok, thanks for the quick answer. So I guess no luck with stock docker-openmatiles-server? I can import a style and tried to put the sprites etc in the styles folder but that didn't work. But I guess this is out of scope here. :)

**Comment by pathmapper** [comment]
> I guess this is out of scope here

Yep.

Are you using https://openmaptiles.com/server/?

If yes, here is described how you could get help:
https://openmaptiles.com/support/

**Comment by 386sx** [comment]
Yes thanks a lot! Very useful hint, I guess I can make it work with that.

**Comment by Tobeyforce** [comment]
Just a quick followup on this thread @pathmapper
I'm attempting to host everything locally, the default source for the natural earth seems to be: https://klokantech.github.io/naturalearthtiles/tiles/natural_earth_2_shaded_relief.raster/{z}/{x}/{y}.png as previously stated.
How would I use it should I download the source locally, e.g from here: https://github.com/lukasmartinelli/naturalearthtiles/releases/download/v1.0/natural_earth_2_shaded_relief.mbtiles
just adding the file in the tiles section of the styles.json didn't work for me:

```
"sources": {
    "openmaptiles": {"type": "vector", "url": "mbtiles://{v3}"},
    "natural_earth_shaded_relief": {
      "maxzoom": 6,
      "tileSize": 256,
      "tiles": [
        "https://github.com/lukasmartinelli/naturalearthtiles/releases/download/v1.0/natural_earth_2_shaded_relief.mbtiles"
      ],
      "type": "raster"
    }
  },
```
Glyphs & sprites seem to be working for me.
